# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SOViewControllerExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SOViewController'

  # Pods for SOViewControllerExample

  target 'SOViewControllerExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SOViewControllerExampleUITests' do
    # Pods for testing
  end

end
